### ISSUE TITLE
Different colors not working

### ISSUE THREAD

**Issue by mhezarei** [chbk/styri-syntax#4]
![image](https://user-images.githubusercontent.com/37423389/47609121-8e4fe780-da45-11e8-8263-ee1a22957de6.png)

I am using styri v0.2.0 and after I updated atom to v1.32.0 the coloring doesn't work

**Comment by chbk** [comment]
This is due to the new Tree-sitter parser that is still under development. You can disable it in Settings > Core > Use Tree Sitter Parsers.

**Comment by mhezarei** [comment]
Thanks a lot

**Comment by chbk** [comment]
&
